apiVersion: apps/v1
kind: Deployment
metadata:
  name: focus-deployment
  labels:
    app: focus
spec:
  replicas: 2
  selector:
    matchLabels:
      app: focus
  template:
    metadata:
      labels:
        app: focus
    spec:
      containers:
        - name: focus
          image: ${{ secrets.AWS_ACCOUNT_ID }}/focus:${{ github.run_number }}
          ports:
            - containerPort: 80

